# Generated by Django 3.2.8 on 2021-11-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211121_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='url',
        ),
    ]
