# Generated by Django 3.2.8 on 2021-12-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CH', 'Cash'), ('CD', 'Card')], default='Cash', max_length=255),
        ),
    ]
