name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    env:
      IMAGE: ghcr.io/${{ github.repository }}:latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -t "${{ env.IMAGE }}" . && 
          docker tag "${{ env.IMAGE }}" "${{ github.repository }}:${GITHUB_SHA::8}"

      - name: Docker login
        run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      - name: Publish
        run: docker push "${{ env.IMAGE }}"
