name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: secret
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    env:
      DB_NAME: test
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      ALLOWED_HOSTS: 127.0.0.1
      DEBUG: 0

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run Migrations
        run: python src/manage.py migrate

      - name: Test Shop App
        run: |
          python src/manage.py test shop

  package:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    env:
      IMAGE: ghcr.io/${{ github.repository }}:latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -t "${{ env.IMAGE }}" . && 
          docker tag "${{ env.IMAGE }}" "${{ github.repository }}:${GITHUB_SHA::8}"

      - name: Docker login
        run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      - name: Publish
        run: docker push "${{ env.IMAGE }}"
